package models

// SDBNOMOR represents the numbering settings table
type SDBNOMOR struct {
	ALIAS   *string `gorm:"column:ALIAS;size:10" json:"alias"`
	PEMISAH *int `gorm:"column:PEMISAH" json:"pemisah"`
	FORMAT1 *int    `gorm:"column:FORMAT1" json:"format1"`
	FORMAT2 *int    `gorm:"column:FORMAT2" json:"format2"`
	FORMAT3 *int    `gorm:"column:FORMAT3" json:"format3"`
	FORMAT4 *int    `gorm:"column:FORMAT4" json:"format4"`
	Contoh  *string `gorm:"column:Contoh;size:100" json:"contoh"`
	Reset   *int    `gorm:"column:Reset" json:"reset"`
	NOSERI  *string `gorm:"column:NOSERI;size:20" json:"noseri"`
	INICAB  *string `gorm:"column:INICAB;size:10" json:"inicab"`
	DigitNomor *string `gorm:"column:DigitNomor;size:10" json:"digitNomor"`
	MyID       *string `gorm:"column:MyID;->;<-:false" json:"-"`
	
	// Dynamic Numbering Fields
	BKK      *string `gorm:"column:BKK;size:50" json:"bkk"`
	NOBKK    *string `gorm:"column:NOBKK;size:50" json:"nobkk"`
	BKM      *string `gorm:"column:BKM;size:50" json:"bkm"`
	NOBKM    *string `gorm:"column:NOBKM;size:50" json:"nobkm"`
	BBM      *string `gorm:"column:BBM;size:50" json:"bbm"`
	NOBBM    *string `gorm:"column:NOBBM;size:50" json:"nobbm"`
	BBK      *string `gorm:"column:BBK;size:50" json:"bbk"`
	NOBBK    *string `gorm:"column:NOBBK;size:50" json:"nobbk"`
	BMM      *string `gorm:"column:BMM;size:50" json:"bmm"`
	NOBMM    *string `gorm:"column:NOBMM;size:50" json:"nobmm"`
	BJK      *string `gorm:"column:BJK;size:50" json:"bjk"`
	NOBJK    *string `gorm:"column:NOBJK;size:50" json:"nobjk"`
	PJL      *string `gorm:"column:PJL;size:50" json:"pjl"`
	NoPJL    *string `gorm:"column:NoPJL;size:50" json:"nopjl"`
	PBL      *string `gorm:"column:PBL;size:50" json:"pbl"`
	NOPBL    *string `gorm:"column:NOPBL;size:50" json:"nopbl"`
	BPPB     *string `gorm:"column:BPPB;size:50" json:"bppb"`
	NOBPPB   *string `gorm:"column:NOBPPB;size:50" json:"nobppb"`
	BPSB     *string `gorm:"column:BPSB;size:50" json:"bpsb"`
	NOBPSB   *string `gorm:"column:NOBPSB;size:50" json:"nobpsb"`
	BBP      *string `gorm:"column:BBP;size:50" json:"bbp"`
	NOBBP    *string `gorm:"column:NOBBP;size:50" json:"nobbp"`
	BPB      *string `gorm:"column:BPB;size:50" json:"bpb"`
	NOBPB    *string `gorm:"column:NOBPB;size:50" json:"nobpb"`
	SPRK     *string `gorm:"column:SPRK;size:50" json:"sprk"`
	NOSPRK   *string `gorm:"column:NOSPRK;size:50" json:"nosprk"`
	BSPRK    *string `gorm:"column:BSPRK;size:50" json:"bsprk"`
	NOBSPRK  *string `gorm:"column:NOBSPRK;size:50" json:"nobsprk"`
	PPL      *string `gorm:"column:PPL;size:50" json:"ppl"`
	NOPPL    *string `gorm:"column:NOPPL;size:50" json:"noppl"`
	BPL      *string `gorm:"column:BPL;size:50" json:"bpl"`
	NOBPL    *string `gorm:"column:NOBPL;size:50" json:"nobpl"`
	PO       *string `gorm:"column:PO;size:50" json:"po"`
	NOPO     *string `gorm:"column:NOPO;size:50" json:"nopo"`
	BPO      *string `gorm:"column:BPO;size:50" json:"bpo"`
	NOBPO    *string `gorm:"column:NOBPO;size:50" json:"nobpo"`
	BP       *string `gorm:"column:BP;size:50" json:"bp"`
	NOBP     *string `gorm:"column:NOBP;size:50" json:"nobp"`
	BPSPRK   *string `gorm:"column:BPSPRK;size:50" json:"bpsprk"`
	NOBPSPRK *string `gorm:"column:NOBPSPRK;size:50" json:"nobpsprk"`
	INS      *string `gorm:"column:INS;size:50" json:"ins"`
	NOINS    *string `gorm:"column:NOINS;size:50" json:"noins"`
	KNS      *string `gorm:"column:KNS;size:50" json:"kns"`
	NOKNS    *string `gorm:"column:NOKNS;size:50" json:"nokns"`
	RPB      *string `gorm:"column:RPB;size:50" json:"rpb"`
	NORPB    *string `gorm:"column:NORPB;size:50" json:"norpb"`
	SPG      *string `gorm:"column:SPG;size:50" json:"spg"`
	NOSPG    *string `gorm:"column:NOSPG;size:50" json:"nospg"`
	OPN      *string `gorm:"column:OPN;size:50" json:"opn"`
	NOOPN    *string `gorm:"column:NOOPN;size:50" json:"noopn"`
	KMS      *string `gorm:"column:KMS;size:50" json:"kms"`
	NOKMS    *string `gorm:"column:NOKMS;size:50" json:"nokms"`
	RBPB     *string `gorm:"column:RBPB;size:50" json:"rbpb"`
	NORBPB   *string `gorm:"column:NORBPB;size:50" json:"norbpb"`
	ENQ      *string `gorm:"column:ENQ;size:50" json:"enq"`
	NOENQ    *string `gorm:"column:NOENQ;size:50" json:"noenq"`
	CR       *string `gorm:"column:CR;size:50" json:"cr"`
	NOCR     *string `gorm:"column:NOCR;size:50" json:"nocr"`
	SO       *string `gorm:"column:SO;size:50" json:"so"`
	NOSO     *string `gorm:"column:NOSO;size:50" json:"noso"`
	RKL      *string `gorm:"column:RKL;size:50" json:"rkl"`
	NORKL    *string `gorm:"column:NORKL;size:50" json:"norkl"`
	SC       *string `gorm:"column:SC;size:50" json:"sc"`
	NOSC     *string `gorm:"column:NOSC;size:50" json:"nosc"`
	SPP      *string `gorm:"column:SPP;size:50" json:"spp"`
	NOSPP    *string `gorm:"column:NOSPP;size:50" json:"nospp"`
	SPB      *string `gorm:"column:SPB;size:50" json:"spb"`
	NOSPB    *string `gorm:"column:NOSPB;size:50" json:"nospb"`
	RSPB     *string `gorm:"column:RSPB;size:50" json:"rspb"`
	NORSPB   *string `gorm:"column:NORSPB;size:50" json:"norspb"`
	INV      *string `gorm:"column:INV;size:50" json:"inv"`
	NOINV    *string `gorm:"column:NOINV;size:50" json:"noinv"`
	PNJ      *string `gorm:"column:PNJ;size:50" json:"pnj"`
	NOPNJ    *string `gorm:"column:NOPNJ;size:50" json:"nopnj"`
	TRC      *string `gorm:"column:TRC;size:50" json:"trc"`
	NOTRC    *string `gorm:"column:NOTRC;size:50" json:"notrc"`
	SHIP     *string `gorm:"column:SHIP;size:50" json:"ship"`
	NOSHIP   *string `gorm:"column:NOSHIP;size:50" json:"noship"`
	TBJ      *string `gorm:"column:TBJ;size:50" json:"tbj"`
	NOTBJ    *string `gorm:"column:NOTBJ;size:50" json:"notbj"`
	RBJ      *string `gorm:"column:RBJ;size:50" json:"rbj"`
	NORBJ    *string `gorm:"column:NORBJ;size:50" json:"norbj"`
	TRS      *string `gorm:"column:TRS;size:50" json:"trs"`
	NOTRS    *string `gorm:"column:NOTRS;size:50" json:"notrs"`
	AKM      *string `gorm:"column:AKM;size:50" json:"akm"`
	RPJ      *string `gorm:"column:RPJ;size:50" json:"rpj"`
	NORPJ    *string `gorm:"column:NORPJ;size:50" json:"norpj"`
	BHN      *string `gorm:"column:BHN;size:50" json:"bhn"`
	NOBHN    *string `gorm:"column:NOBHN;size:50" json:"nobhn"`
	
	// Other string codes
	SPK    *string `gorm:"column:SPK;size:10" json:"spk"`
	RBP    *string `gorm:"column:RBP;size:10" json:"rbp"`
	PR     *string `gorm:"column:PR;size:10" json:"pr"`
	DN     *string `gorm:"column:DN;size:10" json:"dn"`
	OPBJ   *string `gorm:"column:OPBJ;size:10" json:"opbj"`
	KMBJ   *string `gorm:"column:KMBJ;size:10" json:"kmbj"`
	INVC   *string `gorm:"column:INVC;size:10" json:"invc"`
	NoINVC *string `gorm:"column:NoINVC;size:50" json:"noInvc"`
	SPR    *string `gorm:"column:SPR;size:10" json:"spr"`
	NoSPR  *string `gorm:"column:NoSPR;size:50" json:"noSpr"`
	KN     *string `gorm:"column:KN;size:10" json:"kn"`
	NoKN   *string `gorm:"column:NoKN;size:50" json:"noKn"`
	HPD    *string `gorm:"column:HPD;size:10" json:"hpd"`
	PBS    *string `gorm:"column:PBS;size:10" json:"pbs"`
	RPBS   *string `gorm:"column:RPBS;size:10" json:"rpbs"`
	POS    *string `gorm:"column:POS;size:10" json:"pos"`
	HT     *string `gorm:"column:HT;size:10" json:"ht"`
	PT     *string `gorm:"column:PT;size:10" json:"pt"`
	TT     *string `gorm:"column:TT;size:10" json:"tt"`
	KRS    *string `gorm:"column:KRS;size:10" json:"krs"`
	AVT    *string `gorm:"column:AVT;size:10" json:"avt"`
}

// TableName overrides the table name
func (SDBNOMOR) TableName() string {
	return "DBNOMOR"
}
