package export

import (
	"bytes"
	"testing"

	"github.com/stretchr/testify/assert"
)

// TestPDFTableWriter_MinimalRows generates a small (10-row) report and
// asserts the resulting bytes are non-empty and look like a real PDF
// ("%PDF" magic prefix).
func TestPDFTableWriter_MinimalRows(t *testing.T) {
	cols := []string{"ID", "Name", "Active"}
	widths := []float64{20, 60, 30}

	var buf bytes.Buffer
	writer, err := NewPDFTableWriter(&buf, PDFPortrait, cols, widths, "Test Report", "Generated by test")
	assert.NoError(t, err)
	assert.NotNil(t, writer)

	rows := [][]string{
		{"1", "Alice", "Yes"},
		{"2", "Bob", "No"},
		{"3", "Carol", "Yes"},
		{"4", "Dave", "No"},
		{"5", "Erin", "Yes"},
		{"6", "Frank", "No"},
		{"7", "Grace", "Yes"},
		{"8", "Heidi", "No"},
		{"9", "Ivan", "Yes"},
		{"10", "Judy", "No"},
	}
	assert.NoError(t, writer.AddRows(rows))
	assert.NoError(t, writer.Close())

	data := buf.Bytes()
	assert.NotEmpty(t, data, "pdf output should not be empty")
	assert.True(t, bytes.HasPrefix(data, []byte("%PDF")), "pdf output should start with %PDF magic")
}

// TestPDFTableWriter_EmptyRows exercises the "no data rows" edge case:
// the writer should still produce a valid PDF (just the header page).
func TestPDFTableWriter_EmptyRows(t *testing.T) {
	cols := []string{"A", "B"}
	widths := []float64{30, 30}

	var buf bytes.Buffer
	writer, err := NewPDFTableWriter(&buf, PDFPortrait, cols, widths, "Empty Report", "")
	assert.NoError(t, err)
	assert.NoError(t, writer.Close())

	data := buf.Bytes()
	assert.True(t, bytes.HasPrefix(data, []byte("%PDF")))
}

// TestPDFTableWriter_PaginatesLargeReport generates 75 rows so the
// writer must break into at least 3 pages (PDF_ROWS_PER_PAGE = 30).
func TestPDFTableWriter_PaginatesLargeReport(t *testing.T) {
	cols := []string{"N", "V"}
	widths := []float64{20, 80}
	var buf bytes.Buffer
	writer, err := NewPDFTableWriter(&buf, PDFPortrait, cols, widths, "Big", "")
	assert.NoError(t, err)

	rows := make([][]string, 75)
	for i := 0; i < 75; i++ {
		rows[i] = []string{itoa(i), "row-value"}
	}
	assert.NoError(t, writer.AddRows(rows))
	assert.NoError(t, writer.Close())

	assert.NotEmpty(t, buf.Bytes())
	assert.True(t, bytes.HasPrefix(buf.Bytes(), []byte("%PDF")))
}

// TestPDFTableWriter_NilWriterReturnsError ensures the constructor
// rejects a nil io.Writer.
func TestPDFTableWriter_NilWriterReturnsError(t *testing.T) {
	_, err := NewPDFTableWriter(nil, PDFPortrait, []string{"A"}, []float64{10}, "T", "")
	assert.Error(t, err)
}

// TestPDFTableWriter_MismatchedColumnsRejected ensures the constructor
// rejects cols and colWidths of different lengths.
func TestPDFTableWriter_MismatchedColumnsRejected(t *testing.T) {
	_, err := NewPDFTableWriter(&bytes.Buffer{}, PDFPortrait, []string{"A", "B"}, []float64{10}, "T", "")
	assert.Error(t, err)
}

// TestPDFTableWriter_LandscapeOrientation uses PDFLandscape to make
// sure the orientation flag is passed through to fpdf.
func TestPDFTableWriter_LandscapeOrientation(t *testing.T) {
	cols := []string{"A", "B"}
	widths := []float64{100, 100}
	var buf bytes.Buffer
	writer, err := NewPDFTableWriter(&buf, PDFLandscape, cols, widths, "Landscape", "")
	assert.NoError(t, err)
	assert.NoError(t, writer.AddRows([][]string{{"x", "y"}, {"a", "b"}}))
	assert.NoError(t, writer.Close())

	assert.True(t, bytes.HasPrefix(buf.Bytes(), []byte("%PDF")))
}

// TestPDFTableWriter_RowLengthMismatchRejected ensures AddRow rejects
// rows whose length does not match the column count.
func TestPDFTableWriter_RowLengthMismatchRejected(t *testing.T) {
	cols := []string{"A", "B"}
	widths := []float64{10, 10}
	var buf bytes.Buffer
	writer, err := NewPDFTableWriter(&buf, PDFPortrait, cols, widths, "T", "")
	assert.NoError(t, err)
	err = writer.AddRow([]string{"only-one"})
	assert.Error(t, err)
	_ = writer.Close()
}

// TestPDFTableWriter_DoubleCloseReturnsError ensures Close can only be
// called once.
func TestPDFTableWriter_DoubleCloseReturnsError(t *testing.T) {
	cols := []string{"A"}
	widths := []float64{10}
	var buf bytes.Buffer
	writer, err := NewPDFTableWriter(&buf, PDFPortrait, cols, widths, "T", "")
	assert.NoError(t, err)
	assert.NoError(t, writer.Close())
	assert.Error(t, writer.Close())
}

// TestTruncateCell covers the truncateCell helper used by the PDF
// writer to keep cell text inside its column width.
func TestTruncateCell(t *testing.T) {
	assert.Equal(t, "abc", truncateCell("abc", 5), "short string should not be truncated")
	assert.Equal(t, "ab…", truncateCell("abcdef", 3), "long string should be truncated with ellipsis")
	assert.Equal(t, "…", truncateCell("abcdef", 1), "maxRunes<=1 should return single ellipsis")
	assert.Equal(t, "", truncateCell("", 5), "empty string stays empty")
}
