program Trade2Exchange;

uses
  Forms,
  Dialogs,
  FrmUtama in 'FrmUtama.pas' {FrUtama},
  dxDemoUtils in '..\Unit\dxDemoUtils.pas',
  dxEditUtils in '..\Unit\dxEditUtils.pas',
  dxGridMenus in '..\Unit\dxGridMenus.pas',
  MyGlobal in '..\Unit\MyGlobal.pas',
  MyModul in '..\Unit\MyModul.pas' {DM: TDataModule},
  MyProcedure in '..\Unit\MyProcedure.pas',
  FrmReportPreview in '..\ReportPreview\FrmReportPreview.pas' {FrReportPreview},
  FrmBrows in '..\Browsing\FrmBrows.pas' {FrBrows},
  FrmLockPeriod in '..\Setting\Lock Periode\FrmLockPeriod.pas' {FrLockPeriod},
  frmLogin in '..\Setting\Login\frmLogin.pas' {frLogin},
  frmPassword in '..\Setting\Password\frmPassword.pas' {frPassword},
  frmSetupperiode in '..\Setting\Periode\frmSetupperiode.pas' {frSetUpPeriode},
  FrmSubPemakai in '..\Setting\Pemakai\FrmSubPemakai.pas' {FrSubPemakai},
  FrmMenu in '..\Setting\Pemakai\FrmMenu.pas' {FrMenu},
  FrmPemakai in '..\Setting\Pemakai\FrmPemakai.pas' {FrPemakai},
  FrmSetPemakaiGdg in '..\Setting\Pemakai\FrmSetPemakaiGdg.pas' {FrSetPemakaiGdg},
  FrmSubMenu in '..\Setting\Pemakai\FrmSubMenu.pas' {FrSubMenu},
  FrmMenuReport in '..\ReportPreview\FrmMenuReport.pas' {FrMenuReport},
  FrmKonfigurasi in '..\Setting\Konfigurasi\FrmKonfigurasi.pas' {FrKonfigurasi},
  FrmSetBudget in '..\Master\Perkiraan\FrmSetBudget.pas' {FrSetBudGet},
  FrmSetSaldoAwal in '..\Master\Perkiraan\FrmSetSaldoAwal.pas' {FrSetSaldoAwal},
  FrmSetAkesPerkiraan in '..\Setting\AksesPerkiraan\FrmSetAkesPerkiraan.pas' {FrSetAksesPerkiraan},
  FrmSetAkesGudang in '..\Setting\AksesGudang\FrmSetAkesGudang.pas' {FrSetAksesGudang},
  FrmSubValas in '..\Master\Valas\FrmSubValas.pas' {FrSubvalas},
  FrmValas in '..\Master\Valas\FrmValas.pas' {FrValas},
  FrmGudang in '..\Master\Gudang\frmGudang.pas' {FrGudang},
  FrmSubGudang in '..\Master\Gudang\FrmSubGudang.pas' {FrSubGudang},
  FrmPostHutPiut in '..\Setting\Posting\FrmPostHutPiut.pas' {FrPostHutPiut},
  FrmPosting in '..\Setting\Posting\FrmPosting.pas' {FrPosting},
  FrmHutang in '..\Master\Hutang\FrmHutang.pas' {FrHutang},
  FrmHutangAwal in '..\Master\Hutang\FrmHutangAwal.pas' {FrHutangAwal},
  FrmPiutang in '..\Master\Piutang\FrmPiutang.pas' {FrPiutang},
  FrmPiutangAwal in '..\Master\Piutang\FrmPiutangAwal.pas' {FrPiutangAwal},
  FrmGiro in '..\Master\GIRO\FrmGiro.pas' {FrGiro},
  FrmSubGiro in '..\Master\GIRO\FrmSubGiro.pas' {FrSubGiro},
  FrmSubGroup in '..\Master\Group\FrmSubGroup.pas' {FrSubGroup},
  FrmEkspedisi in '..\Master\Ekspedisi\FrmEkspedisi.pas' {FrEksPedisi},
  FrmSubEksPedisi in '..\Master\EksPedisi\FrmSubEksPedisi.pas' {FrSubEksPedisi},
  FrmSubGroup_ in '..\Master\Group\FrmSubGroup_.pas' {FrSubGroup_},
  FrmGroup in '..\Master\Group\FrmGroup.pas' {FrGroup},
  FrmNeraca in '..\Master\Neraca\FrmNeraca.pas' {FrNeraca},
  FrmSubNeraca in '..\Master\Neraca\FrmSubNeraca.pas' {FrSubNeraca},
  FrmLR in '..\Master\LR_HPP\FrmLR.pas' {FrLR},
  FrmSubLR in '..\Master\LR_HPP\FrmSubLR.pas' {FrSubLR},
  FrmAlamatCust in '..\Master\Customer\FrmAlamatCust.pas' {FrAlamatCust},
  FrmBarang in '..\Master\Barang\FrmBarang.pas' {FrBarang},
  FrmSubBarang in '..\Master\Barang\FrmSubBarang.pas' {FrSubBarang},
  FrmBarangJ in '..\Master\Barang\FrmBarangJ.pas' {FrBarangJ},
  FrmSubBarangJ in '..\Master\Barang\FrmSubBarangJ.pas' {frSubBarangJ},
  FrmBarangL in '..\Master\Barang\FrmBarangL.pas' {FrBarangL},
  FrmSubBarangL in '..\Master\Barang\FrmSubBarangL.pas' {FrSubBarangL},
  FrmDepart in '..\Master\Depart\FrmDepart.pas' {FrDepart},
  FrmSubDepart in '..\Master\Depart\FrmSubDepart.pas' {FrSubDepart},
  FrmCustomer in '..\Master\Customer\FrmCustomer.pas' {FrCustomer},
  FrmKoreksiBJ in '..\Trasaksi\Koreksi\FrmKoreksiBJ.pas' {FrKoreksiBJ},
  FrmMainKoreksiBJ in '..\Trasaksi\Koreksi\FrmMainKoreksiBJ.pas' {FrMainKoreksiBJ},
  FrmSubSupplier in '..\Master\Supplier\FrmSubSupplier.pas' {FrSubSupplier},
  FrmSupplier in '..\Master\Supplier\FrmSupplier.pas' {FrSupplier},
  FrmSetForm in '..\Unit\FrmSetForm.pas' {FrSetForm},
  FrmDeposito in '..\Master\DEPOSITO\FrmDeposito.pas' {FrDeposito},
  FrmSubDeposito in '..\Master\DEPOSITO\FrmSubDeposito.pas' {FrSubDeposito},
  FrmHitungUlang in '..\Setting\HitungUlang\FrmHitungUlang.pas' {FrHitungUlang},
  FrmRata2 in '..\Setting\Rata2\FrmRata2.pas' {FrRata2},
  FrmHitungUlangD in '..\Setting\HitungUlangD\FrmHitungUlangD.pas' {FrHitungUlangD},
  FrmAktivitasUser in '..\Setting\Aktivitas User\FrmAktivitasUser.pas' {FrAktivitasUser},
  FrmDialogCetak in '..\Unit\FrmDialogCetak.pas' {FrDialogCetak},
  frmDaftarMenu in '..\Setting\MENU\frmDaftarMenu.pas' {FrDaftarMenu},
  FrmSubDaftarMenu in '..\Setting\MENU\FrmSubDaftarMenu.pas' {FrSubDaftarMenu},
  FrmContact in '..\Master\Contact\FrmContact.pas' {FrContact},
  FrmSubContact in '..\Master\Contact\FrmSubContact.pas' {FrSubContact},
  FrmSubTipeTrans in '..\Master\TipeTrans\FrmSubTipeTrans.pas' {FrSubTipeTrans},
  FrmTipeTrans in '..\Master\TipeTrans\FrmTipeTrans.pas' {FrTipeTrans},
  FrmSubTipeTrans_ in '..\Master\SubTipeTrans\FrmSubTipeTrans_.pas' {FrSubTipeTrans_},
  FrmTipeTrans_ in '..\Master\SubTipeTrans\FrmTipeTrans_.pas' {FrTipeTrans_},
  FrmMainBPPB in '..\Trasaksi\BPPB\FrmMainBPPB.pas' {FrMainBPPB},
  FrmBPPB in '..\Trasaksi\BPPB\FrmBPPB.pas' {FrBPPB},
  FrmMainBPPBT in '..\Trasaksi\BPPB\FrmMainBPPBT.pas' {FrMainBPPBT},
  FrmBPPBT in '..\Trasaksi\BPPB\FrmBPPBT.pas' {FrBPPBT},
  FrmMainPPL in '..\Trasaksi\PPL\FrmMainPPL.pas' {FrMainPPL},
  FrmPPL in '..\Trasaksi\PPL\FrmPPL.pas' {FrPPL},
  FrmMainLunas in '..\Trasaksi\Lunas\FrmMainLunas.pas' {FrMainLunas},
  FrmLunas in '..\Trasaksi\Lunas\FrmLunas.pas' {FrLunas},
  FrmHutPiut in '..\Trasaksi\Lunas\FrmHutPiut.pas' {FrHutPiut},
  FrmSPK in '..\Trasaksi\SPK\FrmSPK.pas' {FrSPK},
  FrmMainPB in '..\Trasaksi\BP\FrmMainPB.pas' {FrMainPB},
  FrmPB in '..\Trasaksi\BP\FrmPB.pas' {FrPB},
  FrmMainRPB in '..\Trasaksi\BP\FrmMainRPB.pas' {FrMainRPB},
  FrmRPB in '..\Trasaksi\BP\FrmRPB.pas' {FrRPB},
  FrmPO in '..\Trasaksi\PO\FrmPO.pas' {FrPO},
  FrmMainPO in '..\Trasaksi\PO\FrmMainPO.pas' {FrMainPO},
  FrmInv in '..\Trasaksi\Beli\FrmInv.pas' {FrInv},
  FrmDPPOut in '..\Trasaksi\Beli\FrmDPPOut.pas' {FrDPPOut},
  FrmMainInv in '..\Trasaksi\Beli\FrmMainInv.pas' {FrMainInv},
  FrmDebetN in '..\Trasaksi\Beli\FrmDebetN.pas' {FrDebetN},
  FrmDebetB in '..\Trasaksi\Beli\FrmDebetB.pas' {FrDebetB},
  FrmMainDebetN in '..\Trasaksi\Beli\FrmMainDebetN.pas' {FrMainDebetN},
  FrmMainBeliRe in '..\Trasaksi\Beli\FrmMainBeliRe.pas' {FrMainBeliRe},
  FrmKoreksi in '..\Trasaksi\Koreksi\FrmKoreksi.pas' {FrKoreksi},
  FrmMainKoreksi in '..\Trasaksi\Koreksi\FrmMainKoreksi.pas' {FrMainKoreksi},
  FrmUbahKemasan in '..\Trasaksi\UbahKemasan\FrmUbahKemasan.pas' {FrUbahKemasan},
  FrmMainUbahKemasan in '..\Trasaksi\UbahKemasan\FrmMainUbahKemasan.pas' {FrMainUbahKemasan},
  FrmUbahKemasanBJ in '..\Trasaksi\UbahKemasan\FrmUbahKemasanBJ.pas' {FrUbahKemasanBJ},
  FrmMainUbahKemasanBJ in '..\Trasaksi\UbahKemasan\FrmMainUbahKemasanBJ.pas' {FrMainUbahKemasanBJ},
  FrmRBeliGdg in '..\Trasaksi\RBeli\FrmRBeliGdg.pas' {FrRBeliGdg},
  FrmMainRBeliGdg in '..\Trasaksi\RBeli\FrmMainRBeliGdg.pas' {FrMainRBeliGdg},
  FrmRBeli in '..\Trasaksi\RBeli\FrmRBeli.pas' {FrRBeli},
  FrmMainRBeli in '..\Trasaksi\RBeli\FrmMainRBeli.pas' {FrMainRBeli},
  FrmBeliNota in '..\Trasaksi\Beli\FrmBeliNota.pas' {FrBeliNota},
  FrmMainBeliNota in '..\Trasaksi\Beli\FrmMainBeliNota.pas' {FrMainBeliNota},
  FrmSubPerkCustSupp in '..\Master\Supplier\FrmSubPerkCustSupp.pas' {FrSubPerkCustSupp},
  FrmMainSubCustomer in '..\Master\Supplier\FrmMainSubCustomer.pas' {FrMainSubCustomer},
  FrmUMHutang in '..\Master\UangMukaHutang\FrmUMHutang.pas' {FrUMHutang},
  FrmUMHutangAwal in '..\Master\UangMukaHutang\FrmUMHutangAwal.pas' {FrUMHutangAwal},
  FrmUMPiutang in '..\Master\UangMukaPiutang\FrmUMPiutang.pas' {FrUMPiutang},
  FrmUMPiutangAwal in '..\Master\UangMukaPiutang\FrmUMPiutangAwal.pas' {FrUMPiutangAwal},
  FrmLoadDataTXT in '..\Trasaksi\LoadDataTXT\FrmLoadDataTXT.pas' {FrLoadDataTXT},
  FrmPenjualan in '..\Trasaksi\Penjualan\FrmPenjualan.pas' {FrPenjualan},
  FrmSubAjcTransfer in '..\Setting\Ajc Transfer\FrmSubAjcTransfer.pas' {FrSubAjcTransfer},
  FrmAjcTransfer in '..\Setting\Ajc Transfer\FrmAjcTransfer.pas' {FrAjcTransfer},
  FrmSubAjcTransferPajak in '..\Setting\Ajc Transfer\FrmSubAjcTransferPajak.pas' {FrSubAjcTransferPajak},
  FrmAjcTransferPajak in '..\Setting\Ajc Transfer\FrmAjcTransferPajak.pas' {FrAjcTransferPajak},
  FrmAlamatCustSupp in '..\Master\Supplier\FrmAlamatCustSupp.pas' {FrAlamatCustSupp},
  FrmBarangCust in '..\Master\Supplier\FrmBarangCust.pas' {FrbarangCust},
  FrmSubKota in '..\Master\Kota\FrmSubKota.pas' {FrSubKota},
  FrmCustSales in '..\Master\Sales\FrmCustSales.pas' {FrCustSales},
  FrmSales in '..\Master\Sales\Frmsales.pas' {Frsales},
  FrmKaryawan in '..\Master\Karyawan\FrmKaryawan.pas' {FrKaryawan},
  FrmSubkaryawan in '..\Master\Karyawan\FrmSubkaryawan.pas' {FrSubKaryawan},
  FrmArea in '..\Master\Area\FrmArea.pas' {FrArea},
  FrmSubArea in '..\Master\Area\FrmSubArea.pas' {FrSubArea},
  FrmMainSO in '..\Trasaksi\SO\FrmMainSO.pas' {FrMainSO},
  FrmSO in '..\Trasaksi\SO\FrmSO.pas' {FrSO},
  FrmBarangCustomer in '..\Master\BarangDanKomisi\Frmbarangcustomer.pas' {FrBarangCustomer},
  FrmBarangDanKomisi in '..\Master\BarangDanKomisi\FrmBarangdanKomisi.pas' {FrbarangdanKomisi},
  FrmKomisiCustomer in '..\Master\BarangDanKomisi\FrmKomisicustomer.pas' {FrKomisiCustomer},
  FrmTargetSales in '..\Master\Sales\FrmTargetSales.pas' {FrTargetSales},
  FrmSPP in '..\Trasaksi\SPP\FrmSPP.pas' {FrSPP},
  FrmMainSPP in '..\Trasaksi\SPP\FrmMainSPP.pas' {FrMainSPP},
  FrmNoBuktiInvoicePL in '..\Trasaksi\InvoicePL\FrmNoBuktiInvoicePL.pas' {FrNoBuktiInvoicePL},
  FrmInvoicePL in '..\Trasaksi\InvoicePL\FrmInvoicePL.pas' {FrInvoicePL},
  FrmMainInvoicePL in '..\Trasaksi\InvoicePL\FrmMainInvoicePL.pas' {FrMainInvoicePL},
  FrmSPBKirim in '..\Trasaksi\SPB\FrmSPBKirim.pas' {FrSPBKirim},
  FrmMainSPB in '..\Trasaksi\SPB\FrmMainSPB.pas' {FrMainSPB},
  FrmSPB in '..\Trasaksi\SPB\FrmSPB.pas' {FrSPB},
  FrmSPPProses in '..\Trasaksi\SPP\FrmSPPProses.pas' {FrSPPProses},
  FrmSPBProses in '..\Trasaksi\SPB\FrmSPBProses.pas' {FrSPBProses},
  FrmLokasi in '..\Master\Gudang\FrmLokasi.pas' {FrLokasi},
  FrmMainSPBRJual in '..\Trasaksi\SPBRJual\FrmMainSPBRjual.pas' {FrMainSPBRjual},
  FrmSPBRJual in '..\Trasaksi\SPBRJual\FrmSPBRJual.pas' {FrSPBRJual},
  FrmSPBRjualKirim in '..\Trasaksi\SPBRJual\FrmSPBRJualKirim.pas' {FrSPBRJualKirim},
  FrmInvoicePLProsesTransaksi in '..\Trasaksi\InvoicePL\FrmInvoicePLProsesTransaksi.pas' {FrInvoicePLProsesTransaksi},
  FrmInvoicePLProses in '..\Trasaksi\InvoicePL\FrmInvoicePLProses.pas' {FrInvoicePLProses},
  FrmTglKirimPO in '..\Trasaksi\PO\FrmTglKirimPO.pas' {FrTglKirimPO},
  FrmKreditB in '..\Trasaksi\KreditN\FrmKreditB.pas' {FrKreditB},
  FrmKreditN in '..\Trasaksi\KreditN\FrmKreditN.pas' {FrKreditN},
  FrmMainKreditN in '..\Trasaksi\KreditN\FrmMainKreditN.pas' {FrMainKreditN},
  FrmJabatan in '..\Master\Jabatan\FrmJabatan.pas' {FrJabatan},
  FrmSubJabatan in '..\Master\Jabatan\FrmSubJabatan.pas' {FrSubJabatan},
  FrmBiaya in '..\Master\Biaya\FrmBiaya.pas' {FrBiaya},
  FrmSubBiaya in '..\Master\Biaya\FrmSubBiaya.pas' {FrSubBiaya},
  FrmMainTransfer in '..\Trasaksi\Transfer\FrmMainTransfer.pas' {FrMainTransfer},
  FrmTransfer in '..\Trasaksi\Transfer\FrmTransfer.pas' {FrTransfer},
  FrmMainRSPB in '..\Trasaksi\ReturSPB\FrmMainRSPB.pas' {FrMainRSPB},
  FrmRSPB in '..\Trasaksi\ReturSPB\FrmRSPB.pas' {FrRSPB},
  FrmRSPBKirim in '..\Trasaksi\ReturSPB\FrmRSPBKirim.pas' {FrRSPBKirim},
  FrmDasboard in '..\Dasboard\FrmDasboard.pas' {FrDasboard},
  FrmFakturPajak in '..\Trasaksi\FakturPajak\FrmFakturPajak.pas' {FrFakturPajak},
  FrmIsiNoFPJ in '..\Trasaksi\FakturPajak\FrmIsiNoFPJ.pas' {FrIsiNoFPJ},
  FrmIsiNoFPJRBeli in '..\Trasaksi\FakturPajakRBeli\FrmIsiNoFPJRBeli.pas' {FrIsiNoFPJRBeli},
  FrmHPPProduksi in '..\Master\HPPProduksi\frmHPPProduksi.pas' {FrHPPProduksi},
  FrmSubHPPProduksi in '..\Master\HPPProduksi\FrmSubHppProduksi.pas' {FrSubHPPProduksi},
  FrmFakturPajakRbeli in '..\Trasaksi\FakturPajakRBeli\FrmFakturPajakRBeli.pas' {FrFakturPajakRbeli},
  FrmInvoiceRPJ in '..\Trasaksi\InvoiceRPJ\FrmInvoiceRPJ.pas' {FrInvoiceRPJ},
  FrmMainInvoiceRPJ in '..\Trasaksi\InvoiceRPJ\FrmMainInvoiceRPJ.pas' {FrMainInvoiceRPJ},
  FrmMainPBSampel in '..\Trasaksi\BPSample\FrmMainPBSampel.pas' {FrMainPBSampel},
  FrmMainRPBSampel in '..\Trasaksi\BPSample\FrmMainRPBSampel.pas' {FrMainRPBSampel},
  FrmPBSampel in '..\Trasaksi\BPSample\FrmPBSampel.pas' {FrPBSampel},
  FrmRPBSampel in '..\Trasaksi\BPSample\FrmRPBSampel.pas' {FrRPBSampel},
  FrmSubBarangProses in '..\Master\Barang\FrmSubBarangProses.pas' {FrSubBarangProses},
  FrmSubJenisTambahan_ in '..\Master\JenisTambahan\FrmSubJenisTambahan_.pas' {FrSubJenisTambahan_},
  FrmJenisTambahan in '..\Master\JenisTambahan\FrmJenisTambahan.pas' {FrJenisTambahan},
  FrmSubJenisTambahan in '..\Master\JenisTambahan\FrmSubJenisTambahan.pas' {FrSubJenisTambahan},
  FrmSubGroup_JnsTambah in '..\Master\Group\FrmSubGroup_JnsTambah.pas' {FrSubGroup_JnsTambah},
  FrmPembayaran in '..\Trasaksi\JualKasir\FrmPembayaran.pas' {FrPembayaran},
  FrmJualKasir in '..\Trasaksi\JualKasir\FrmJualKasir.pas' {FrJualKasir},
  FrmMainJualKasir in '..\Trasaksi\JualKasir\FrmMainJualKasir.pas' {FrMainJualKasir},
  FrmSubDiskonHarian in '..\Master\DiskonHarian\FrmSubDiskonHarian.pas' {frSubDiskonHarian},
  FrmDiskonHarian in '..\Master\DiskonHarian\FrmDiskonHarian.pas' {FrDiskonHarian},
  FrmJualKasirOrder in '..\Trasaksi\JualKasirOrder\FrmJualKasirOrder.pas' {FrJualKasirOrder},
  FrmSubPajak in '..\Master\Pajak\FrmSubPajak.pas' {frSubPajak},
  FrmPajak in '..\Master\Pajak\FrmPajak.pas' {FrPajak},
  FrmSPKPesan in '..\Trasaksi\SPKPesan\FrmSPKPesan.pas' {FrSPKPesan},
  FrmMainSPKPesan in '..\Trasaksi\SPKPesan\FrmMainSPKPesan.pas' {FrMainSPKPesan},
  FrmSPKPesanProses in '..\Trasaksi\SPKPesan\FrmSPKPesanProses.pas' {FrSPKPesanProses},
  FrmMainHasilPPesan in '..\Trasaksi\HasilProduksiPesan\FrmMainHasilPPesan.pas' {FrMainHasilPPesan},
  FrmHasilPPesan in '..\Trasaksi\HasilProduksiPesan\FrmHasilPPesan.pas' {FrHasilPPesan},
  FrmPostingJurnalOto in '..\Setting\PostingJurnalOto\FrmPostingJurnalOto.pas' {FrPostingJurnalOto},
  FrmBOM in '..\Trasaksi\BOM\FrmBOM.pas' {FrBOM},
  FrmBOMGanti in '..\Trasaksi\BOM\FrmBOMGanti.pas' {FrBOMGanti},
  FrmSubBOM in '..\Trasaksi\BOM\FrmSUBBOM.pas' {FrSubBOM},
  FrmSubBOMGanti in '..\Trasaksi\BOM\FrmSUBBOMGanti.pas' {FrSubBOMGanti},
  FrmMainSPK in '..\Trasaksi\SPK\FrmMainSPK.pas' {FrMainSPK},
  FrmDevisi in '..\Master\Devisi\FrmDevisi.pas' {FrDevisi},
  FrmSubDevisi in '..\Master\Devisi\FrmSubDevisi.pas' {FrSubdevisi},
  FrmDevGudang in '..\Master\Devisi\FrmDevGudang.pas' {FrdevGudang},
  FrmSubjenisCust in '..\Master\JenisCustomer\FrmSubJenisCust.pas' {FrSubJenisCust},
  FrmJenisCust in '..\Master\JenisCustomer\frmJenisCust.pas' {FrJenisCust},
  FrmHargaJual in '..\Master\Barang\FrmHargaJual.pas' {FrHargaJual},
  FrmSubValas_ in '..\Master\Valas\FrmSubValas_.pas' {FrSubValas_},
  FrmMainPROut in '..\Trasaksi\CLOSINGPR\FrmMainPROUT.pas' {FrMainPROut},
  FrmRevPO in '..\Trasaksi\RevisiPO\FrmRevPO.pas' {FrRevPO},
  FrmMainPORev in '..\Trasaksi\RevisiPO\FrmMainPORev.pas' {FrMainPORev},
  FrmTglKirimRevPO in '..\Trasaksi\RevisiPO\FrmTglKirimRevPO.pas' {FrTglKirimRevPO},
  FrmMainPOOut in '..\Trasaksi\CLOSINGPO\FrmMainPOOut.pas' {FrMainPOOut},
  FrmMainSORev in '..\Trasaksi\REVISISO\FrmMainSORev.pas' {FrMainSORev},
  FrmRevSO in '..\Trasaksi\REVISISO\FrmRevSO.pas' {FrRevSO},
  FrmMainCloseSO in '..\Trasaksi\CLOSINGSO\FrmMainCloseSO.pas' {FrMainCloseSO},
  FrmSubASM in '..\Master\ASM\FrmSubASM.pas' {FrSubASM},
  FrmASM in '..\Master\ASM\frmASM.pas' {FrASM},
  FrmSubHargaJual in '..\Master\HargaJual\FrmSubHargaJual.pas' {FrSubHargaJual},
  FrmTempStockBOM in '..\Trasaksi\SPK\FrmTempStockBOM.pas' {FrTempStockBOM},
  FrmMainHasilP in '..\Trasaksi\Hasil Produksi\FrmMainHasilP.pas' {FrMainHasilP},
  FrmHasilP in '..\Trasaksi\Hasil Produksi\FrmHasilP.pas' {FrHasilP},
  FrmUMInvoicePLProses in '..\Trasaksi\InvoicePL\FrmUMInvoicePLProses.pas' {FrUMInvoicePLProses},
  FrmMainUMInvoicePL in '..\Trasaksi\InvoicePL\FrmMainUMInvoicePL.pas' {FrMainUMInvoicePL},
  FrmUMInvoicePL in '..\Trasaksi\InvoicePL\FrmUMInvoicePL.pas' {FrUMInvoicePL},
  FrmProses in '..\Master\Master Proses\frmProses.pas' {FrProses},
  FrmSubProses in '..\Master\Master Proses\FrmSubProses.pas' {FrSubProses},
  FrmJadwalPRD in '..\Master\JADWAL PRD\frmJadwalPRD.pas' {FrJadwalPRD},
  FrmSubJadwalPRD in '..\Master\JADWAL PRD\FrmSubJadwalPRD.pas' {FrSubJadwalPRD},
  FrmBiayaProses in '..\Master\BiayaProses\frmBiayaProses.pas' {FrBiayaProses},
  FrmSubBiayaProses in '..\Master\BiayaProses\FrmSubBiayaProses.pas' {FrSubBiayaProses},
  FrmSubTarifTenaker in '..\Master\TarifTenaker\FrmSubTarifTenaker.pas' {FrSubTarifTenaker},
  FrmTarifTenaker in '..\Master\TarifTenaker\frmTarifTenaker.pas' {FrTarifTenaker},
  FrmMainJadwalProduksi in '..\Trasaksi\JadwalProduksi\FrmMainJadwalProduksi.pas' {FrMainJadwalProduksi},
  FrmSubTenaker in '..\Master\TarifTenaker\FrmSubTenaker.pas' {FrSubTenaker},
  FrmTenaker in '..\Master\TarifTenaker\FrmTenaker.pas' {FrTenaker},
  FrmKoreksiDK in '..\Trasaksi\KoreksiDK\FrmKoreksiDK.pas' {FrKoreksiDK},
  FrmMainKoreksiDk in '..\Trasaksi\KoreksiDK\FrmMainKoreksiDk.pas' {FrMainKoreksiDK},
  FrmMainBeliBahan in '..\Trasaksi\Beli\FrmMainBeliBahan.pas' {FrMainBeliBahan},
  FrmBuatBeliBAhan in '..\Trasaksi\Beli\FrmBuatBeliBahan.pas' {FrBuatBeliBAhan},
  FrmProduksi in '..\Trasaksi\Produksi\FrmProduksi.pas' {FrProduksi},
  FrmMainKasBank in '..\Trasaksi\KasBank\FrmMainKasBank.pas' {FrMainKasBank},
  FrmKasBank in '..\Trasaksi\KasBank\FrmKasBank.pas' {FrKasBank},
  FrmKasBankGiro in '..\Trasaksi\KasBank\FrmKasBankGiro.pas' {FrKasBankGiro},
  FrmKasBankAktiva in '..\Trasaksi\KasBank\FrmKasBankAktiva.pas' {frKasBankAktiva},
  FrmKasBankHutPiut in '..\Trasaksi\KasBank\FrmKasBankHutPiut.pas' {FrKasBankHutPiut},
  FrmKasBankDeposito in '..\Trasaksi\KasBank\FrmKasBankDeposito.pas' {FrKasBankDeposito},
  FrmMainMemorial in '..\Trasaksi\Memorial\FrmMainMemorial.pas' {FrMainMemorial},
  FrmMemorial in '..\Trasaksi\Memorial\FrmMemorial.pas' {FrMemorial},
  FrmMemorialGiro in '..\Trasaksi\Memorial\FrmMemorialGiro.pas' {FrMemorialGiro},
  FrmMemorialHutPiut in '..\Trasaksi\Memorial\FrmMemorialHutPiut.pas' {FrMemorialHutPiut},
  FrmMemorialAktiva in '..\Trasaksi\Memorial\FrmMemorialAktiva.pas' {frMemorialAktiva},
  FrmBon in '..\Trasaksi\Bon Sementara\FrmBon.pas' {FrBon},
  FrmSubBon in '..\Trasaksi\Bon Sementara\FrmSubBon.pas' {FrSubBon},
  FrmMainRJual in '..\Trasaksi\ReturJual\FrmMainRJual.pas' {FrMainRJual},
  FrmRJual in '..\Trasaksi\ReturJual\FrmRJual.pas' {FrRJual},
  FrmRInvoicePLProsesTransaksi in '..\Trasaksi\ReturJual\FrmRInvoicePLProsesTransaksi.pas' {FrRInvoicePLProsesTransaksi},
  FrmMainBeli in '..\Trasaksi\Beli\FrmMainBeli.pas' {FrMainBeli},
  FrmBeli in '..\Trasaksi\Beli\FrmBeli.pas' {FrBeli},
  FrmBuatBeli in '..\Trasaksi\Beli\FrmBuatBeli.pas' {FrBuatBeli},
  FrmBeliBahan in '..\Trasaksi\Beli\FrmBeliBahan.pas' {FrBeliBahan},
  FrmMainJual in '..\Trasaksi\Penjualan\FrmMainJual.pas' {FrMainJual},
  FrmMainPBJadi in '..\Trasaksi\BPJadi\FrmMainPBJadi.pas' {FrMainPBJadi},
  FrmPBJadi in '..\Trasaksi\BPJadi\FrmPBJadi.pas' {FrPBJadi},
  FrmBeliRe in '..\Trasaksi\Beli\FrmBeliRe.pas' {FrBeliRe},
  FrmProsesProduksi in '..\Trasaksi\Proses Produksi\FrmProsesProduksi.pas' {FrProsesProduksi},
  FrmSubProsesProduksi in '..\Trasaksi\Proses Produksi\FrmSubProsesProduksi.pas' {FrSubProsesProduksi},
  FrmKota in '..\Master\Kota\FrmKota.pas' {FrKota},
  FrmDesain in '..\Trasaksi\Desain\FrmDesain.pas' {FrDesain},
  FrmSubDesain in '..\Trasaksi\Desain\FrmSubDesain.pas' {FrSubDesain},
  FrmSubLapArusKas in '..\Master\ArusKas\FrmSubLapArusKas.pas' {FrSubLapArusKas},
  FrmArusKas in '..\Master\ArusKas\FrmArusKas.pas' {FrArusKas},
  FrmLapArusKas in '..\Master\ArusKas\FrmLapArusKas.pas' {FrLapArusKas},
  FrmSubArusKas in '..\Master\ArusKas\FrmSubArusKas.pas' {FrSubArusKas},
  FrmSubArusKas_ in '..\Master\ArusKas\FrmSubArusKas_.pas' {FrSubArusKas_},
  FrmSubPerkiraan in '..\Master\Perkiraan\FrmSubPerkiraan.pas' {FrSubPerkiraan},
  FrmPerkiraan in '..\Master\Perkiraan\FrmPerkiraan.pas' {FrPerkiraan},
  FrmProsesTutupBuku in '..\Setting\TutupBuku\FrmProsesTutupBuku.pas' {FrTutupBuku},
  FrmSubAktivaFk in '..\Master\AktivaTetap\FrmSubAktivaFk.pas' {frSubAktivaFk},
  FrmAktivaFk in '..\Master\AktivaTetap\FrmAktivaFk.pas' {FrAktivaFk},
  FrmSetSaldoAktivaFk in '..\Master\AktivaTetap\FrmSetSaldoAktivaFk.pas' {FrSetSaldoAktivaFk},
  FrmSubAktiva in '..\Master\AktivaTetap\FrmSubAktiva.pas' {frSubAktiva},
  FrmAktiva in '..\Master\AktivaTetap\FrmAktiva.pas' {FrAktiva},
  FrmSetSaldoAktiva in '..\Master\AktivaTetap\FrmSetSaldoAktiva.pas' {FrSetSaldoAktiva},
  FrmPostingUlangJurnalOto in '..\Setting\PostingUlangJurnalOto\FrmPostingUlangJurnalOto.pas' {FrPostingUlangJurnalOto},
  FrmPerkCustSupp in '..\Master\Supplier\FrmPerkCustSupp.pas' {FrPerkCustSupp},
  FrmSubCustomerP in '..\Master\Supplier\FrmSubCustomerP.pas' {FrSubCustomerP},
  FrmSubCustomer in '..\Master\Customer\FrmSubCustomer.pas' {FrSubCustomer},
  FrmMainProduksi in '..\Trasaksi\Produksi\FrmMainProduksi.pas' {FrMainProduksi},
  FrmSubMesin in '..\Master\Mesin\FrmSubMesin.pas' {FrSubMesin},
  FrmMainFinishing in '..\Trasaksi\Produksi\FrmMainFinishing.pas' {FrMainFinishing},
  FrmFinishing in '..\Trasaksi\Produksi\FrmFinishing.pas' {FrFinishing},
  FrmMesin in '..\Master\Mesin\frmMesin.pas' {FrMesin},
  FrmJenisMesin in '..\Master\Mesin\frmJenisMesin.pas' {FrJenisMesin},
  FrmSubJenisMesin in '..\Master\Mesin\FrmSubJenisMesin.pas' {FrSubJenisMesin},
  FrmPBLain in '..\Trasaksi\BP\FrmPBLain.pas' {FrPBLain},
  FrmMainPBLain in '..\Trasaksi\BP\FrmMainPBLain.pas' {FrMainPBLain},
  FrmRPBLain in '..\Trasaksi\BP\FrmRPBLain.pas' {FrRPBLain},
  FrmMainRPBLain in '..\Trasaksi\BP\FrmMainRPBLain.pas' {FrMainRPBLain},
  FrmProsesTutupBukuFiskal in '..\Setting\TutupBuku\FrmProsesTutupBukuFiskal.pas' {FrTutupBukuFiskal},
  FrmMemorialLain in '..\Trasaksi\MemorialLain\FrmMemorialLain.pas' {FrMemorialLain},
  FrmMainMemorialLain in '..\Trasaksi\MemorialLain\FrmMainMemorialLain.pas' {FrMainMemorialLain},
  FrmMemorialAktivaLain in '..\Trasaksi\MemorialLain\FrmMemorialAktivaLain.pas' {frMemorialAktivaLain},
  FrmMemorialGiroLain in '..\Trasaksi\MemorialLain\FrmMemorialGiroLain.pas' {FrMemorialGiroLain},
  FrmMemorialHutPiutLain in '..\Trasaksi\MemorialLain\FrmMemorialHutPiutLain.pas' {FrMemorialHutPiutLain},
  FrmPPn in '..\master\PPn\FrmPPn.pas' {FrPPn},
  FrmSubPPn in '..\Master\PPn\FrmSubPPn.pas' {frSubPPn},
  FrmMainAnggaran in '..\Trasaksi\Anggaran\FrmMainAnggaran.pas' {FrMainAnggaran},
  FrmAnggaran in '..\Trasaksi\Anggaran\FrmAnggaran.pas' {FrAnggaran};

{$R *.res}

var F:textfile;
    i:integer;
begin
  AssignFile(F,'Connection.dat');
  {$I-}
  Reset(F);
  {$I+}
  if IOResult <> 0 then
     MessageDlg('File Koneksi tidak ada',
      mtInformation, [mbOk], 0)
  else
  begin
     i:=0;
     while not eof(F) do
     begin
        Readln(F, Koneksi[i]);
        inc(i);
     end;
     CloseFile(F);
  end;
  Application.Initialize;
  Application.Title := 'Trade Exchange 2011';
  Application.CreateForm(TFrUtama, FrUtama);
  Application.CreateForm(TDM, DM);
  Application.CreateForm(TFrSetForm, FrSetForm);
  DM.MyStock.Connected:=False;
  //DM.MyStock.ConnectionString:=Koneksi[0];
  Dm.MyStock.ConnectionString:='Provider=SQLOLEDB.1;Password='+yPassword+
    ';Persist Security Info=True;User ID='+Usd+';'+Koneksi[0];//Initial Catalog='+MyDb+';
  Dm.MyStockmkt.ConnectionString:='Provider=SQLOLEDB.1;Password='+yPassword+
    ';Persist Security Info=True;User ID='+Usd+';'+Koneksi[1];//Initial Catalog='+MyDb+';
    {Dm.MyStock.ConnectionString:='Provider=SQLOLEDB.1;Integrated Security=SSPI;Use Encryption for Data=False;Password='+yPassword+
    ';Persist Security Info=True;User ID='+Usd+';'+Koneksi[0];//Initial Catalog='+MyDb+';
  Dm.MyStockmkt.ConnectionString:='Provider=SQLOLEDB.1;Password='+yPassword+
    ';Persist Security Info=True;User ID='+Usd+';'+Koneksi[1];//Initial Catalog='+MyDb+';    }
  DM.MyStock.Connected:=True;
  Application.Run;
end.
