/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KaryawanLayoutRouteImport } from './routes/karyawan/_layout'
import { Route as AdminLayoutRouteImport } from './routes/admin/_layout'
import { Route as publicDocsRouteImport } from './routes/(public)/docs'
import { Route as publicDocsIndexRouteImport } from './routes/(public)/docs/index'
import { Route as publicDocsThemeRouteImport } from './routes/(public)/docs/theme'
import { Route as publicDocsOverlayRouteImport } from './routes/(public)/docs/overlay'
import { Route as publicDocsNavigationRouteImport } from './routes/(public)/docs/navigation'
import { Route as publicDocsLayoutRouteImport } from './routes/(public)/docs/layout'
import { Route as publicDocsFormRouteImport } from './routes/(public)/docs/form'
import { Route as publicDocsFeedbackRouteImport } from './routes/(public)/docs/feedback'
import { Route as publicDocsDataRouteImport } from './routes/(public)/docs/data'
import { Route as KaryawanLayoutDashboardIndexRouteImport } from './routes/karyawan/_layout/dashboard/index'
import { Route as AdminLayoutUsersIndexRouteImport } from './routes/admin/_layout/users/index'
import { Route as AdminLayoutReportsIndexRouteImport } from './routes/admin/_layout/reports/index'
import { Route as AdminLayoutDocumentsIndexRouteImport } from './routes/admin/_layout/documents/index'
import { Route as AdminLayoutDashboardIndexRouteImport } from './routes/admin/_layout/dashboard/index'
import { Route as publicauthRegisterIndexRouteImport } from './routes/(public)/(auth)/register/index'
import { Route as publicauthLoginIndexRouteImport } from './routes/(public)/(auth)/login/index'
import { Route as AdminLayoutBerkasPerusahaanRouteImport } from './routes/admin/_layout/berkas/perusahaan'
import { Route as AdminLayoutBerkasMenuRouteImport } from './routes/admin/_layout/berkas/menu'
import { Route as AdminLayoutReportsPermissionReportIndexRouteImport } from './routes/admin/_layout/reports/permission-report/index'
import { Route as AdminLayoutMasterDataUserManagementIndexRouteImport } from './routes/admin/_layout/master-data/user-management/index'
import { Route as AdminLayoutMasterDataConfigLogsIndexRouteImport } from './routes/admin/_layout/master-data/config-logs/index'
import { Route as AdminLayoutMasterDataActivityLogsIndexRouteImport } from './routes/admin/_layout/master-data/activity-logs/index'
import { Route as AdminLayoutAccountingKasbankIndexRouteImport } from './routes/admin/_layout/accounting/kasbank/index'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KaryawanLayoutRoute = KaryawanLayoutRouteImport.update({
  id: '/karyawan/_layout',
  path: '/karyawan',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLayoutRoute = AdminLayoutRouteImport.update({
  id: '/admin/_layout',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const publicDocsRoute = publicDocsRouteImport.update({
  id: '/(public)/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const publicDocsIndexRoute = publicDocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => publicDocsRoute,
} as any)
const publicDocsThemeRoute = publicDocsThemeRouteImport.update({
  id: '/theme',
  path: '/theme',
  getParentRoute: () => publicDocsRoute,
} as any)
const publicDocsOverlayRoute = publicDocsOverlayRouteImport.update({
  id: '/overlay',
  path: '/overlay',
  getParentRoute: () => publicDocsRoute,
} as any)
const publicDocsNavigationRoute = publicDocsNavigationRouteImport.update({
  id: '/navigation',
  path: '/navigation',
  getParentRoute: () => publicDocsRoute,
} as any)
const publicDocsLayoutRoute = publicDocsLayoutRouteImport.update({
  id: '/layout',
  path: '/layout',
  getParentRoute: () => publicDocsRoute,
} as any)
const publicDocsFormRoute = publicDocsFormRouteImport.update({
  id: '/form',
  path: '/form',
  getParentRoute: () => publicDocsRoute,
} as any)
const publicDocsFeedbackRoute = publicDocsFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => publicDocsRoute,
} as any)
const publicDocsDataRoute = publicDocsDataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => publicDocsRoute,
} as any)
const KaryawanLayoutDashboardIndexRoute =
  KaryawanLayoutDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => KaryawanLayoutRoute,
  } as any)
const AdminLayoutUsersIndexRoute = AdminLayoutUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutReportsIndexRoute = AdminLayoutReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutDocumentsIndexRoute =
  AdminLayoutDocumentsIndexRouteImport.update({
    id: '/documents/',
    path: '/documents/',
    getParentRoute: () => AdminLayoutRoute,
  } as any)
const AdminLayoutDashboardIndexRoute =
  AdminLayoutDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AdminLayoutRoute,
  } as any)
const publicauthRegisterIndexRoute = publicauthRegisterIndexRouteImport.update({
  id: '/(public)/(auth)/register/',
  path: '/register/',
  getParentRoute: () => rootRouteImport,
} as any)
const publicauthLoginIndexRoute = publicauthLoginIndexRouteImport.update({
  id: '/(public)/(auth)/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLayoutBerkasPerusahaanRoute =
  AdminLayoutBerkasPerusahaanRouteImport.update({
    id: '/berkas/perusahaan',
    path: '/berkas/perusahaan',
    getParentRoute: () => AdminLayoutRoute,
  } as any)
const AdminLayoutBerkasMenuRoute = AdminLayoutBerkasMenuRouteImport.update({
  id: '/berkas/menu',
  path: '/berkas/menu',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutReportsPermissionReportIndexRoute =
  AdminLayoutReportsPermissionReportIndexRouteImport.update({
    id: '/reports/permission-report/',
    path: '/reports/permission-report/',
    getParentRoute: () => AdminLayoutRoute,
  } as any)
const AdminLayoutMasterDataUserManagementIndexRoute =
  AdminLayoutMasterDataUserManagementIndexRouteImport.update({
    id: '/master-data/user-management/',
    path: '/master-data/user-management/',
    getParentRoute: () => AdminLayoutRoute,
  } as any)
const AdminLayoutMasterDataConfigLogsIndexRoute =
  AdminLayoutMasterDataConfigLogsIndexRouteImport.update({
    id: '/master-data/config-logs/',
    path: '/master-data/config-logs/',
    getParentRoute: () => AdminLayoutRoute,
  } as any)
const AdminLayoutMasterDataActivityLogsIndexRoute =
  AdminLayoutMasterDataActivityLogsIndexRouteImport.update({
    id: '/master-data/activity-logs/',
    path: '/master-data/activity-logs/',
    getParentRoute: () => AdminLayoutRoute,
  } as any)
const AdminLayoutAccountingKasbankIndexRoute =
  AdminLayoutAccountingKasbankIndexRouteImport.update({
    id: '/accounting/kasbank/',
    path: '/accounting/kasbank/',
    getParentRoute: () => AdminLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/docs': typeof publicDocsRouteWithChildren
  '/admin': typeof AdminLayoutRouteWithChildren
  '/karyawan': typeof KaryawanLayoutRouteWithChildren
  '/docs/data': typeof publicDocsDataRoute
  '/docs/feedback': typeof publicDocsFeedbackRoute
  '/docs/form': typeof publicDocsFormRoute
  '/docs/layout': typeof publicDocsLayoutRoute
  '/docs/navigation': typeof publicDocsNavigationRoute
  '/docs/overlay': typeof publicDocsOverlayRoute
  '/docs/theme': typeof publicDocsThemeRoute
  '/docs/': typeof publicDocsIndexRoute
  '/admin/berkas/menu': typeof AdminLayoutBerkasMenuRoute
  '/admin/berkas/perusahaan': typeof AdminLayoutBerkasPerusahaanRoute
  '/login/': typeof publicauthLoginIndexRoute
  '/register/': typeof publicauthRegisterIndexRoute
  '/admin/dashboard/': typeof AdminLayoutDashboardIndexRoute
  '/admin/documents/': typeof AdminLayoutDocumentsIndexRoute
  '/admin/reports/': typeof AdminLayoutReportsIndexRoute
  '/admin/users/': typeof AdminLayoutUsersIndexRoute
  '/karyawan/dashboard/': typeof KaryawanLayoutDashboardIndexRoute
  '/admin/accounting/kasbank/': typeof AdminLayoutAccountingKasbankIndexRoute
  '/admin/master-data/activity-logs/': typeof AdminLayoutMasterDataActivityLogsIndexRoute
  '/admin/master-data/config-logs/': typeof AdminLayoutMasterDataConfigLogsIndexRoute
  '/admin/master-data/user-management/': typeof AdminLayoutMasterDataUserManagementIndexRoute
  '/admin/reports/permission-report/': typeof AdminLayoutReportsPermissionReportIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminLayoutRouteWithChildren
  '/karyawan': typeof KaryawanLayoutRouteWithChildren
  '/docs/data': typeof publicDocsDataRoute
  '/docs/feedback': typeof publicDocsFeedbackRoute
  '/docs/form': typeof publicDocsFormRoute
  '/docs/layout': typeof publicDocsLayoutRoute
  '/docs/navigation': typeof publicDocsNavigationRoute
  '/docs/overlay': typeof publicDocsOverlayRoute
  '/docs/theme': typeof publicDocsThemeRoute
  '/docs': typeof publicDocsIndexRoute
  '/admin/berkas/menu': typeof AdminLayoutBerkasMenuRoute
  '/admin/berkas/perusahaan': typeof AdminLayoutBerkasPerusahaanRoute
  '/login': typeof publicauthLoginIndexRoute
  '/register': typeof publicauthRegisterIndexRoute
  '/admin/dashboard': typeof AdminLayoutDashboardIndexRoute
  '/admin/documents': typeof AdminLayoutDocumentsIndexRoute
  '/admin/reports': typeof AdminLayoutReportsIndexRoute
  '/admin/users': typeof AdminLayoutUsersIndexRoute
  '/karyawan/dashboard': typeof KaryawanLayoutDashboardIndexRoute
  '/admin/accounting/kasbank': typeof AdminLayoutAccountingKasbankIndexRoute
  '/admin/master-data/activity-logs': typeof AdminLayoutMasterDataActivityLogsIndexRoute
  '/admin/master-data/config-logs': typeof AdminLayoutMasterDataConfigLogsIndexRoute
  '/admin/master-data/user-management': typeof AdminLayoutMasterDataUserManagementIndexRoute
  '/admin/reports/permission-report': typeof AdminLayoutReportsPermissionReportIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/(public)/docs': typeof publicDocsRouteWithChildren
  '/admin/_layout': typeof AdminLayoutRouteWithChildren
  '/karyawan/_layout': typeof KaryawanLayoutRouteWithChildren
  '/(public)/docs/data': typeof publicDocsDataRoute
  '/(public)/docs/feedback': typeof publicDocsFeedbackRoute
  '/(public)/docs/form': typeof publicDocsFormRoute
  '/(public)/docs/layout': typeof publicDocsLayoutRoute
  '/(public)/docs/navigation': typeof publicDocsNavigationRoute
  '/(public)/docs/overlay': typeof publicDocsOverlayRoute
  '/(public)/docs/theme': typeof publicDocsThemeRoute
  '/(public)/docs/': typeof publicDocsIndexRoute
  '/admin/_layout/berkas/menu': typeof AdminLayoutBerkasMenuRoute
  '/admin/_layout/berkas/perusahaan': typeof AdminLayoutBerkasPerusahaanRoute
  '/(public)/(auth)/login/': typeof publicauthLoginIndexRoute
  '/(public)/(auth)/register/': typeof publicauthRegisterIndexRoute
  '/admin/_layout/dashboard/': typeof AdminLayoutDashboardIndexRoute
  '/admin/_layout/documents/': typeof AdminLayoutDocumentsIndexRoute
  '/admin/_layout/reports/': typeof AdminLayoutReportsIndexRoute
  '/admin/_layout/users/': typeof AdminLayoutUsersIndexRoute
  '/karyawan/_layout/dashboard/': typeof KaryawanLayoutDashboardIndexRoute
  '/admin/_layout/accounting/kasbank/': typeof AdminLayoutAccountingKasbankIndexRoute
  '/admin/_layout/master-data/activity-logs/': typeof AdminLayoutMasterDataActivityLogsIndexRoute
  '/admin/_layout/master-data/config-logs/': typeof AdminLayoutMasterDataConfigLogsIndexRoute
  '/admin/_layout/master-data/user-management/': typeof AdminLayoutMasterDataUserManagementIndexRoute
  '/admin/_layout/reports/permission-report/': typeof AdminLayoutReportsPermissionReportIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/docs'
    | '/admin'
    | '/karyawan'
    | '/docs/data'
    | '/docs/feedback'
    | '/docs/form'
    | '/docs/layout'
    | '/docs/navigation'
    | '/docs/overlay'
    | '/docs/theme'
    | '/docs/'
    | '/admin/berkas/menu'
    | '/admin/berkas/perusahaan'
    | '/login/'
    | '/register/'
    | '/admin/dashboard/'
    | '/admin/documents/'
    | '/admin/reports/'
    | '/admin/users/'
    | '/karyawan/dashboard/'
    | '/admin/accounting/kasbank/'
    | '/admin/master-data/activity-logs/'
    | '/admin/master-data/config-logs/'
    | '/admin/master-data/user-management/'
    | '/admin/reports/permission-report/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/karyawan'
    | '/docs/data'
    | '/docs/feedback'
    | '/docs/form'
    | '/docs/layout'
    | '/docs/navigation'
    | '/docs/overlay'
    | '/docs/theme'
    | '/docs'
    | '/admin/berkas/menu'
    | '/admin/berkas/perusahaan'
    | '/login'
    | '/register'
    | '/admin/dashboard'
    | '/admin/documents'
    | '/admin/reports'
    | '/admin/users'
    | '/karyawan/dashboard'
    | '/admin/accounting/kasbank'
    | '/admin/master-data/activity-logs'
    | '/admin/master-data/config-logs'
    | '/admin/master-data/user-management'
    | '/admin/reports/permission-report'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/(public)/docs'
    | '/admin/_layout'
    | '/karyawan/_layout'
    | '/(public)/docs/data'
    | '/(public)/docs/feedback'
    | '/(public)/docs/form'
    | '/(public)/docs/layout'
    | '/(public)/docs/navigation'
    | '/(public)/docs/overlay'
    | '/(public)/docs/theme'
    | '/(public)/docs/'
    | '/admin/_layout/berkas/menu'
    | '/admin/_layout/berkas/perusahaan'
    | '/(public)/(auth)/login/'
    | '/(public)/(auth)/register/'
    | '/admin/_layout/dashboard/'
    | '/admin/_layout/documents/'
    | '/admin/_layout/reports/'
    | '/admin/_layout/users/'
    | '/karyawan/_layout/dashboard/'
    | '/admin/_layout/accounting/kasbank/'
    | '/admin/_layout/master-data/activity-logs/'
    | '/admin/_layout/master-data/config-logs/'
    | '/admin/_layout/master-data/user-management/'
    | '/admin/_layout/reports/permission-report/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  publicDocsRoute: typeof publicDocsRouteWithChildren
  AdminLayoutRoute: typeof AdminLayoutRouteWithChildren
  KaryawanLayoutRoute: typeof KaryawanLayoutRouteWithChildren
  publicauthLoginIndexRoute: typeof publicauthLoginIndexRoute
  publicauthRegisterIndexRoute: typeof publicauthRegisterIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/karyawan/_layout': {
      id: '/karyawan/_layout'
      path: '/karyawan'
      fullPath: '/karyawan'
      preLoaderRoute: typeof KaryawanLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_layout': {
      id: '/admin/_layout'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/docs': {
      id: '/(public)/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof publicDocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/docs/': {
      id: '/(public)/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof publicDocsIndexRouteImport
      parentRoute: typeof publicDocsRoute
    }
    '/(public)/docs/theme': {
      id: '/(public)/docs/theme'
      path: '/theme'
      fullPath: '/docs/theme'
      preLoaderRoute: typeof publicDocsThemeRouteImport
      parentRoute: typeof publicDocsRoute
    }
    '/(public)/docs/overlay': {
      id: '/(public)/docs/overlay'
      path: '/overlay'
      fullPath: '/docs/overlay'
      preLoaderRoute: typeof publicDocsOverlayRouteImport
      parentRoute: typeof publicDocsRoute
    }
    '/(public)/docs/navigation': {
      id: '/(public)/docs/navigation'
      path: '/navigation'
      fullPath: '/docs/navigation'
      preLoaderRoute: typeof publicDocsNavigationRouteImport
      parentRoute: typeof publicDocsRoute
    }
    '/(public)/docs/layout': {
      id: '/(public)/docs/layout'
      path: '/layout'
      fullPath: '/docs/layout'
      preLoaderRoute: typeof publicDocsLayoutRouteImport
      parentRoute: typeof publicDocsRoute
    }
    '/(public)/docs/form': {
      id: '/(public)/docs/form'
      path: '/form'
      fullPath: '/docs/form'
      preLoaderRoute: typeof publicDocsFormRouteImport
      parentRoute: typeof publicDocsRoute
    }
    '/(public)/docs/feedback': {
      id: '/(public)/docs/feedback'
      path: '/feedback'
      fullPath: '/docs/feedback'
      preLoaderRoute: typeof publicDocsFeedbackRouteImport
      parentRoute: typeof publicDocsRoute
    }
    '/(public)/docs/data': {
      id: '/(public)/docs/data'
      path: '/data'
      fullPath: '/docs/data'
      preLoaderRoute: typeof publicDocsDataRouteImport
      parentRoute: typeof publicDocsRoute
    }
    '/karyawan/_layout/dashboard/': {
      id: '/karyawan/_layout/dashboard/'
      path: '/dashboard'
      fullPath: '/karyawan/dashboard/'
      preLoaderRoute: typeof KaryawanLayoutDashboardIndexRouteImport
      parentRoute: typeof KaryawanLayoutRoute
    }
    '/admin/_layout/users/': {
      id: '/admin/_layout/users/'
      path: '/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminLayoutUsersIndexRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/reports/': {
      id: '/admin/_layout/reports/'
      path: '/reports'
      fullPath: '/admin/reports/'
      preLoaderRoute: typeof AdminLayoutReportsIndexRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/documents/': {
      id: '/admin/_layout/documents/'
      path: '/documents'
      fullPath: '/admin/documents/'
      preLoaderRoute: typeof AdminLayoutDocumentsIndexRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/dashboard/': {
      id: '/admin/_layout/dashboard/'
      path: '/dashboard'
      fullPath: '/admin/dashboard/'
      preLoaderRoute: typeof AdminLayoutDashboardIndexRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/(public)/(auth)/register/': {
      id: '/(public)/(auth)/register/'
      path: '/register'
      fullPath: '/register/'
      preLoaderRoute: typeof publicauthRegisterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/(auth)/login/': {
      id: '/(public)/(auth)/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof publicauthLoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_layout/berkas/perusahaan': {
      id: '/admin/_layout/berkas/perusahaan'
      path: '/berkas/perusahaan'
      fullPath: '/admin/berkas/perusahaan'
      preLoaderRoute: typeof AdminLayoutBerkasPerusahaanRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/berkas/menu': {
      id: '/admin/_layout/berkas/menu'
      path: '/berkas/menu'
      fullPath: '/admin/berkas/menu'
      preLoaderRoute: typeof AdminLayoutBerkasMenuRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/reports/permission-report/': {
      id: '/admin/_layout/reports/permission-report/'
      path: '/reports/permission-report'
      fullPath: '/admin/reports/permission-report/'
      preLoaderRoute: typeof AdminLayoutReportsPermissionReportIndexRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/master-data/user-management/': {
      id: '/admin/_layout/master-data/user-management/'
      path: '/master-data/user-management'
      fullPath: '/admin/master-data/user-management/'
      preLoaderRoute: typeof AdminLayoutMasterDataUserManagementIndexRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/master-data/config-logs/': {
      id: '/admin/_layout/master-data/config-logs/'
      path: '/master-data/config-logs'
      fullPath: '/admin/master-data/config-logs/'
      preLoaderRoute: typeof AdminLayoutMasterDataConfigLogsIndexRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/master-data/activity-logs/': {
      id: '/admin/_layout/master-data/activity-logs/'
      path: '/master-data/activity-logs'
      fullPath: '/admin/master-data/activity-logs/'
      preLoaderRoute: typeof AdminLayoutMasterDataActivityLogsIndexRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/accounting/kasbank/': {
      id: '/admin/_layout/accounting/kasbank/'
      path: '/accounting/kasbank'
      fullPath: '/admin/accounting/kasbank/'
      preLoaderRoute: typeof AdminLayoutAccountingKasbankIndexRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
  }
}

interface publicDocsRouteChildren {
  publicDocsDataRoute: typeof publicDocsDataRoute
  publicDocsFeedbackRoute: typeof publicDocsFeedbackRoute
  publicDocsFormRoute: typeof publicDocsFormRoute
  publicDocsLayoutRoute: typeof publicDocsLayoutRoute
  publicDocsNavigationRoute: typeof publicDocsNavigationRoute
  publicDocsOverlayRoute: typeof publicDocsOverlayRoute
  publicDocsThemeRoute: typeof publicDocsThemeRoute
  publicDocsIndexRoute: typeof publicDocsIndexRoute
}

const publicDocsRouteChildren: publicDocsRouteChildren = {
  publicDocsDataRoute: publicDocsDataRoute,
  publicDocsFeedbackRoute: publicDocsFeedbackRoute,
  publicDocsFormRoute: publicDocsFormRoute,
  publicDocsLayoutRoute: publicDocsLayoutRoute,
  publicDocsNavigationRoute: publicDocsNavigationRoute,
  publicDocsOverlayRoute: publicDocsOverlayRoute,
  publicDocsThemeRoute: publicDocsThemeRoute,
  publicDocsIndexRoute: publicDocsIndexRoute,
}

const publicDocsRouteWithChildren = publicDocsRoute._addFileChildren(
  publicDocsRouteChildren,
)

interface AdminLayoutRouteChildren {
  AdminLayoutBerkasMenuRoute: typeof AdminLayoutBerkasMenuRoute
  AdminLayoutBerkasPerusahaanRoute: typeof AdminLayoutBerkasPerusahaanRoute
  AdminLayoutDashboardIndexRoute: typeof AdminLayoutDashboardIndexRoute
  AdminLayoutDocumentsIndexRoute: typeof AdminLayoutDocumentsIndexRoute
  AdminLayoutReportsIndexRoute: typeof AdminLayoutReportsIndexRoute
  AdminLayoutUsersIndexRoute: typeof AdminLayoutUsersIndexRoute
  AdminLayoutAccountingKasbankIndexRoute: typeof AdminLayoutAccountingKasbankIndexRoute
  AdminLayoutMasterDataActivityLogsIndexRoute: typeof AdminLayoutMasterDataActivityLogsIndexRoute
  AdminLayoutMasterDataConfigLogsIndexRoute: typeof AdminLayoutMasterDataConfigLogsIndexRoute
  AdminLayoutMasterDataUserManagementIndexRoute: typeof AdminLayoutMasterDataUserManagementIndexRoute
  AdminLayoutReportsPermissionReportIndexRoute: typeof AdminLayoutReportsPermissionReportIndexRoute
}

const AdminLayoutRouteChildren: AdminLayoutRouteChildren = {
  AdminLayoutBerkasMenuRoute: AdminLayoutBerkasMenuRoute,
  AdminLayoutBerkasPerusahaanRoute: AdminLayoutBerkasPerusahaanRoute,
  AdminLayoutDashboardIndexRoute: AdminLayoutDashboardIndexRoute,
  AdminLayoutDocumentsIndexRoute: AdminLayoutDocumentsIndexRoute,
  AdminLayoutReportsIndexRoute: AdminLayoutReportsIndexRoute,
  AdminLayoutUsersIndexRoute: AdminLayoutUsersIndexRoute,
  AdminLayoutAccountingKasbankIndexRoute:
    AdminLayoutAccountingKasbankIndexRoute,
  AdminLayoutMasterDataActivityLogsIndexRoute:
    AdminLayoutMasterDataActivityLogsIndexRoute,
  AdminLayoutMasterDataConfigLogsIndexRoute:
    AdminLayoutMasterDataConfigLogsIndexRoute,
  AdminLayoutMasterDataUserManagementIndexRoute:
    AdminLayoutMasterDataUserManagementIndexRoute,
  AdminLayoutReportsPermissionReportIndexRoute:
    AdminLayoutReportsPermissionReportIndexRoute,
}

const AdminLayoutRouteWithChildren = AdminLayoutRoute._addFileChildren(
  AdminLayoutRouteChildren,
)

interface KaryawanLayoutRouteChildren {
  KaryawanLayoutDashboardIndexRoute: typeof KaryawanLayoutDashboardIndexRoute
}

const KaryawanLayoutRouteChildren: KaryawanLayoutRouteChildren = {
  KaryawanLayoutDashboardIndexRoute: KaryawanLayoutDashboardIndexRoute,
}

const KaryawanLayoutRouteWithChildren = KaryawanLayoutRoute._addFileChildren(
  KaryawanLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  publicDocsRoute: publicDocsRouteWithChildren,
  AdminLayoutRoute: AdminLayoutRouteWithChildren,
  KaryawanLayoutRoute: KaryawanLayoutRouteWithChildren,
  publicauthLoginIndexRoute: publicauthLoginIndexRoute,
  publicauthRegisterIndexRoute: publicauthRegisterIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
