package models

// SDBNOMOR represents the numbering settings table
type SDBNOMOR struct {
	ALIAS   *string `gorm:"column:ALIAS;size:10" json:"alias"`
	PEMISAH *int    `gorm:"column:PEMISAH" json:"pemisah"`
	FORMAT1 *int    `gorm:"column:FORMAT1" json:"format1"`
	FORMAT2 *int    `gorm:"column:FORMAT2" json:"format2"`
	FORMAT3 *int    `gorm:"column:FORMAT3" json:"format3"`
	FORMAT4 *int    `gorm:"column:FORMAT4" json:"format4"`
	Contoh  *string `gorm:"column:Contoh;size:100" json:"contoh"`
	Reset   *int    `gorm:"column:Reset" json:"reset"`
	NOSERI  *string `gorm:"column:NOSERI;size:20" json:"noseri"`
	INICAB  *string `gorm:"column:INICAB;size:10" json:"inicab"`
	DigitNomor *string `gorm:"column:DigitNomor;size:10" json:"digitNomor"`
	
	// Dynamic Numbering Fields
	BKK      *int    `gorm:"column:BKK" json:"bkk"`
	NOBKK    *string `gorm:"column:NOBKK;size:50" json:"nobkk"`
	BKM      *int    `gorm:"column:BKM" json:"bkm"`
	NOBKM    *string `gorm:"column:NOBKM;size:50" json:"nobkm"`
	BBM      *int    `gorm:"column:BBM" json:"bbm"`
	NOBBM    *string `gorm:"column:NOBBM;size:50" json:"nobbm"`
	BBK      *int    `gorm:"column:BBK" json:"bbk"`
	NOBBK    *string `gorm:"column:NOBBK;size:50" json:"nobbk"`
	BMM      *int    `gorm:"column:BMM" json:"bmm"`
	NOBMM    *string `gorm:"column:NOBMM;size:50" json:"nobmm"`
	BJK      *int    `gorm:"column:BJK" json:"bjk"`
	NOBJK    *string `gorm:"column:NOBJK;size:50" json:"nobjk"`
	PJL      *int    `gorm:"column:PJL" json:"pjl"`
	NoPJL    *string `gorm:"column:NoPJL;size:50" json:"nopjl"`
	PBL      *int    `gorm:"column:PBL" json:"pbl"`
	NOPBL    *string `gorm:"column:NOPBL;size:50" json:"nopbl"`
	BPPB     *int    `gorm:"column:BPPB" json:"bppb"`
	NOBPPB   *string `gorm:"column:NOBPPB;size:50" json:"nobppb"`
	BPSB     *int    `gorm:"column:BPSB" json:"bpsb"`
	NOBPSB   *string `gorm:"column:NOBPSB;size:50" json:"nobpsb"`
	BBP      *int    `gorm:"column:BBP" json:"bbp"`
	NOBBP    *string `gorm:"column:NOBBP;size:50" json:"nobbp"`
	BPB      *int    `gorm:"column:BPB" json:"bpb"`
	NOBPB    *string `gorm:"column:NOBPB;size:50" json:"nobpb"`
	SPRK     *int    `gorm:"column:SPRK" json:"sprk"`
	NOSPRK   *string `gorm:"column:NOSPRK;size:50" json:"nosprk"`
	BSPRK    *int    `gorm:"column:BSPRK" json:"bsprk"`
	NOBSPRK  *string `gorm:"column:NOBSPRK;size:50" json:"nobsprk"`
	PPL      *int    `gorm:"column:PPL" json:"ppl"`
	NOPPL    *string `gorm:"column:NOPPL;size:50" json:"noppl"`
	BPL      *int    `gorm:"column:BPL" json:"bpl"`
	NOBPL    *string `gorm:"column:NOBPL;size:50" json:"nobpl"`
	PO       *int    `gorm:"column:PO" json:"po"`
	NOPO     *string `gorm:"column:NOPO;size:50" json:"nopo"`
	BPO      *int    `gorm:"column:BPO" json:"bpo"`
	NOBPO    *string `gorm:"column:NOBPO;size:50" json:"nobpo"`
	BP       *int    `gorm:"column:BP" json:"bp"`
	NOBP     *string `gorm:"column:NOBP;size:50" json:"nobp"`
	BPSPRK   *int    `gorm:"column:BPSPRK" json:"bpsprk"`
	NOBPSPRK *string `gorm:"column:NOBPSPRK;size:50" json:"nobsprk"`
	INS      *int    `gorm:"column:INS" json:"ins"`
	NOINS    *string `gorm:"column:NOINS;size:50" json:"noins"`
	KNS      *int    `gorm:"column:KNS" json:"kns"`
	NOKNS    *string `gorm:"column:NOKNS;size:50" json:"nokns"`
	RPB      *int    `gorm:"column:RPB" json:"rpb"`
	NORPB    *string `gorm:"column:NORPB;size:50" json:"norpb"`
	SPG      *int    `gorm:"column:SPG" json:"spg"`
	NOSPG    *string `gorm:"column:NOSPG;size:50" json:"nospg"`
	OPN      *int    `gorm:"column:OPN" json:"opn"`
	NOOPN    *string `gorm:"column:NOOPN;size:50" json:"noopn"`
	KMS      *int    `gorm:"column:KMS" json:"kms"`
	NOKMS    *string `gorm:"column:NOKMS;size:50" json:"nokms"`
	RBPB     *int    `gorm:"column:RBPB" json:"rbpb"`
	NORBPB   *string `gorm:"column:NORBPB;size:50" json:"norbpb"`
	ENQ      *int    `gorm:"column:ENQ" json:"enq"`
	NOENQ    *string `gorm:"column:NOENQ;size:50" json:"noenq"`
	CR       *int    `gorm:"column:CR" json:"cr"`
	NOCR     *string `gorm:"column:NOCR;size:50" json:"nocr"`
	SO       *int    `gorm:"column:SO" json:"so"`
	NOSO     *string `gorm:"column:NOSO;size:50" json:"noso"`
	RKL      *int    `gorm:"column:RKL" json:"rkl"`
	NORKL    *string `gorm:"column:NORKL;size:50" json:"norkl"`
	SC       *int    `gorm:"column:SC" json:"sc"`
	NOSC     *string `gorm:"column:NOSC;size:50" json:"nosc"`
	SPP      *int    `gorm:"column:SPP" json:"spp"`
	NOSPP    *string `gorm:"column:NOSPP;size:50" json:"nospp"`
	SPB      *int    `gorm:"column:SPB" json:"spb"`
	NOSPB    *string `gorm:"column:NOSPB;size:50" json:"nospb"`
	RSPB     *int    `gorm:"column:RSPB" json:"rspb"`
	NORSPB   *string `gorm:"column:NORSPB;size:50" json:"norspb"`
	INV      *int    `gorm:"column:INV" json:"inv"`
	NOINV    *string `gorm:"column:NOINV;size:50" json:"noinv"`
	PNJ      *int    `gorm:"column:PNJ" json:"pnj"`
	NOPNJ    *string `gorm:"column:NOPNJ;size:50" json:"nopnj"`
	TRC      *int    `gorm:"column:TRC" json:"trc"`
	NOTRC    *string `gorm:"column:NOTRC;size:50" json:"notrc"`
	SHIP     *int    `gorm:"column:SHIP" json:"ship"`
	NOSHIP   *string `gorm:"column:NOSHIP;size:50" json:"noship"`
	TBJ      *int    `gorm:"column:TBJ" json:"tbj"`
	NOTBJ    *string `gorm:"column:NOTBJ;size:50" json:"notbj"`
	RBJ      *int    `gorm:"column:RBJ" json:"rbj"`
	NORBJ    *string `gorm:"column:NORBJ;size:50" json:"norbj"`
	TRS      *int    `gorm:"column:TRS" json:"trs"`
	NOTRS    *string `gorm:"column:NOTRS;size:50" json:"notrs"`
	AKM      *int    `gorm:"column:AKM" json:"akm"`
	RPJ      *int    `gorm:"column:RPJ" json:"rpj"`
	NORPJ    *string `gorm:"column:NORPJ;size:50" json:"norpj"`
	BHN      *int    `gorm:"column:BHN" json:"bhn"`
	NOBHN    *string `gorm:"column:NOBHN;size:50" json:"nobhn"`
	
	// Other string codes
	SPK    *string `gorm:"column:SPK;size:10" json:"spk"`
	RBP    *string `gorm:"column:RBP;size:10" json:"rbp"`
	PR     *string `gorm:"column:PR;size:10" json:"pr"`
	DN     *string `gorm:"column:DN;size:10" json:"dn"`
	OPBJ   *string `gorm:"column:OPBJ;size:10" json:"opbj"`
	KMBJ   *string `gorm:"column:KMBJ;size:10" json:"kmbj"`
	INVC   *string `gorm:"column:INVC;size:10" json:"invc"`
	NoINVC *string `gorm:"column:NoINVC;size:50" json:"noInvc"`
	SPR    *string `gorm:"column:SPR;size:10" json:"spr"`
	NoSPR  *string `gorm:"column:NoSPR;size:50" json:"noSpr"`
	KN     *string `gorm:"column:KN;size:10" json:"kn"`
	NoKN   *string `gorm:"column:NoKN;size:50" json:"noKn"`
	HPD    *string `gorm:"column:HPD;size:10" json:"hpd"`
	PBS    *string `gorm:"column:PBS;size:10" json:"pbs"`
	RPBS   *string `gorm:"column:RPBS;size:10" json:"rpbs"`
	POS    *string `gorm:"column:POS;size:10" json:"pos"`
	HT     *string `gorm:"column:HT;size:10" json:"ht"`
	PT     *string `gorm:"column:PT;size:10" json:"pt"`
	TT     *string `gorm:"column:TT;size:10" json:"tt"`
	KRS    *string `gorm:"column:KRS;size:10" json:"krs"`
	AVT    *string `gorm:"column:AVT;size:10" json:"avt"`
}

// TableName overrides the table name
func (SDBNOMOR) TableName() string {
	return "DBNOMOR"
}
